server:
  port: 8082 

spring:
  h2:
    console:
      enabled: true
      
  datasource:
    url: jdbc:h2:mem:testDB # h2 database 連接位址
    driver-class-name: org.h2.Driver # 配置driver
    username: test
    password: test
  sql:
    init:
      encoding: utf-8 # SQL scripts encoding.

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate: 
        ddl-auto: none
    
# CoinDesk API URL
coindesk:
  url: https://api.coindesk.com/v1/bpi/currentprice.json