server:
  port: 8082 # 伺服器的port號

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testDB # h2 database 連接位址
    driver-class-name: org.h2.Driver # 配置driver
    username: test # database 用戶名
    password: test # database 密碼

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect